version: '3.9'


services:
  app:
    container_name: atom-chat-code-challenge
    env_file:
      - .env
    # command: tail -f /dev/null
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"